### PR TITLE
Add master toleration

### PR DESCRIPTION
**Pull request by r7vme**
and switch to community accepted master role label

In favor https://github.com/giantswarm/aws-terraform/commit/28067f79d4e13fa3ee0ade7b57aec44d12bb4e31

### CODE REVIEW

**Comment by r7vme** [comment]
@calvix @corest pls review

**Comment by calvix** [comment]
this is for the host cluster and I don't think we have this new label in host cluster anywhere.
I cant say if this break stuff or not

**Comment by r7vme** [comment]
@calvix you're right. So at the moment just added comment and later when all clusters will have this label we can switch to it.

**Comment by r7vme** [comment]
Merging.

**Pull request merged**
